enum ACTIONS {
  WHY,
  RECOM_COLOR,
  RECOM_OTHER,
  HANDLE_EXCHANGE,
  POSITIVE_RETURN_OPTIONS,
  NEGATIVE_RETURN_OPTIONS,
  POSITIVE_CASHBACK_METHODS,
  NEGATIVE_CASHBACK_METHODS,
  LUCK,
  POSITIVE_METHOD_CONFIRMATION,
  CASH_RETURN_CONFIRMATION,
  VOUCHER_CONFIRMATION,
  REVER_MARKETPLACE,
  EXCHANGE_CONFIRMATION,
  EXCHANGE_COURIER_CONFIRMATION,
  EXCHANGE_SIZE_METHODS,
  EXCHANGE_SIZE_CONFIRMATION,
}

class FSM {
  action: ACTIONS;

  constructor() {
    this.action = ACTIONS.WHY;
  }

  goToAction(action: ACTIONS) {
    console.log('go to action', action);
    this.action = action;
  }
}

export { FSM, ACTIONS };
